# Generated by Django 4.1.4 on 2023-12-31 20:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='feature_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_feature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_recent',
            field=models.BooleanField(default=False),
        ),
    ]
